server:
  port: 1005
spring:
  aop:
    proxy-target-class: true
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
      routes:
      - id: server1
        uri: lb://server1
        predicates:
        - Path= /server1/**
        filters:
        - StripPrefix= 1
      - id: server2
        uri: lb://server2
        predicates:
        - Path= /server2/**
        filters:
        - StripPrefix= 1
      - id: redis
        uri: lb://redis
        predicates:
        - Path= /redis/**
        filters:
        - StripPrefix= 1
      - id: thymeleaf
        uri: lb://thymeleaf
        predicates:
        - Path= /thymeleaf/**
        filters:
        - StripPrefix= 1
