server:
  port: 9000
spring:
  application:
    name: zuul
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  host:
    connect-timeout-millis: 3000
  routes:
    mysql:
      path: /mysql/**
      serviceId: mysql

