server:
  port: 1002
spring:
  aop:
    proxy-target-class: true
  cloud:
    gateway:
      default-filters:
      routes:
        - id: server1
          uri: lb://server1
          predicates:
            - Path= /server1/**
          filters:
            - StripPrefix= 1
        - id: server2
          uri: lb://server2
          predicates:
            - Path= /server2/**
          filters:
            - StripPrefix= 1
        - id: redis
          uri: lb://redis
          predicates:
            - Path= /redis/**
          filters:
            - StripPrefix= 1
        - id: thymeleaf
          uri: lb://thymeleaf
          predicates:
            - Path= /thymeleaf/**
          filters:
            - StripPrefix= 1
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          semaphore:
            timeoutInMilliseconds: 5000
          thread:
            timeoutInMilliseconds: 240000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 20
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 100
